[build]
  command = "npx update-browserslist-db@latest && npm run build"
  publish = "/build"
  base ="/frontend_react"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  CI = "false"